# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it hasn't had new comments in the last 3 months. It will be closed if no further activity occurs.
  If you still need assistance with this issue, or believe it shouldn't be closed, please respond with a new comment to let us know.
  
  Thank you all for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
